### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by juabergon** [jnoc/telegram-username-checker#4]
$ python check.py
Traceback (most recent call last):
  File "C:\Users\check.py", line 96, in <module>
    main()
  File "C:\Users\check.py", line 68, in main
    print('''
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-16: character maps to <undefined>

**Comment by ilnarildarovuch** [comment]
Change codec to utf-8
